FROM mysql

MAINTAINER Flavio Goncalves Toledo <fgtoledo1@gmail.com>


# ENV MYSQL_USER=flavio
# MYSQL_DATABASE=projetojava
# MYSQL_ROOT_PASSWORD='Fgt010383@'

ADD ./cria_tabela.sql /docker-entrypoint-initdb.d
